name: cleaning-scripts

on: [push]

jobs:
  lint:
    name: Lint python
    runs-on: ubuntu-18.04
    working-directory: python

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Lint
        run: |
          cd python
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=100 --statistics
          black --check --line-length=100 --verbose .

  publish:
    name: Build and publish python
    runs-on: ubuntu-18.04
    needs: build
    if: github.ref == 'refs/heads/master'
    working-directory: python

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd python
          python setup.py sdist bdist_wheel
          ls -l dist/*.tar.gz
          twine upload dist/*.tar.gz
